export interface PresentInfo {
  id: number;
  name: string;
  description?: string;
  weight: string;
  price: string;
  folder: string;
  images: string[];
}

export const db: PresentInfo[] = [
  {
    id: 1,
    name: `Кубик Золотой`,
    description: ``,
    weight: `200`,
    price: `270`,
    folder: "03_kubik_zolotoi",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 2,
    name: `Фонарик "Кто Там"`,
    description: ``,
    weight: `320`,
    price: `490`,
    folder: "02_kto_tam",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 3,
    name: `Лесной Домик`,
    description: ``,
    weight: `215`,
    price: `300`,
    folder: "04_lesnoi_domik",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 4,
    name: `Колокольчик`,
    description: ``,
    weight: `280`,
    price: `400`,
    folder: "01_kolokolchik",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 5,
    name: `Праздник Маленький`,
    description: ``,
    weight: `310`,
    price: `450`,
    folder: "05_prazdnik_malenkii",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 6,
    name: `С Новым Годом!`,
    description: ``,
    weight: `320`,
    price: `500`,
    folder: "06_s_novym_godom",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 7,
    name: `Кубик Маленький`,
    description: ``,
    weight: `165`,
    price: `235`,
    folder: "07_kubik_malenkii",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 8,
    name: `Сумочка`,
    description: ``,
    weight: `250`,
    price: `345`,
    folder: "08_sumochka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 9,
    name: `Конфетка`,
    description: ``,
    weight: `250`,
    price: `360`,
    folder: "09_konfetka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 10,
    name: `Конфетка-Раскраска`,
    description: ``,
    weight: `260`,
    price: `365`,
    folder: "10_konfetka_raskraska",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 11,
    name: `Недорогой Подарок`,
    description: ``,
    weight: `300`,
    price: `430`,
    folder: "11_nedorogoi_podarok",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 12,
    name: `Белочка`,
    description: ``,
    weight: `330`,
    price: `500`,
    folder: "12_belochka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 13,
    name: `Почта Деда Мороза`,
    description: ``,
    weight: `315`,
    price: `480`,
    folder: "13_pochta_deda_moroza",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 14,
    name: `Крепкая Дружба`,
    description: ``,
    weight: `260`,
    price: `400`,
    folder: "14_krepkaya_druzhba",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 15,
    name: `Веселье Маленькое`,
    description: ``,
    weight: `290`,
    price: `475`,
    folder: "15_vesele_malenkoe",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 16,
    name: `Бумажные Снежинки`,
    description: ``,
    weight: `215`,
    price: `345`,
    folder: "16_bumazhnye_snezhinki",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 17,
    name: `Кукурузный Домик`,
    description: ``,
    weight: `375`,
    price: `590`,
    folder: "17_kukuruznyi_domik",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 18,
    name: `Снежный Вечер`,
    description: ``,
    weight: `405`,
    price: `590`,
    folder: "18_snezhnyi_vecher",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 19,
    name: `Кубик Большой`,
    description: ``,
    weight: `410`,
    price: `600`,
    folder: "19_kubik_bolshoi",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 20,
    name: `Эко Сумочка`,
    description: ``,
    weight: `410`,
    price: `700`,
    folder: "20_eko_sumochka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 21,
    name: `Фонарик`,
    description: ``,
    weight: `310`,
    price: `535`,
    folder: "21_fonarik",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 22,
    name: `Сказочный Замок`,
    description: ``,
    weight: `485`,
    price: `750`,
    folder: "22_skazochnyi_zamok",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 23,
    name: `Друзья`,
    description: ``,
    weight: `340`,
    price: `550`,
    folder: "23_druziya",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 24,
    name: `Веселье Большое`,
    description: ``,
    weight: `450`,
    price: `700`,
    folder: "24_veselie_bolshoe",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 25,
    name: `Детки / Снеговики`,
    description: ``,
    weight: `250`,
    price: `400`,
    folder: "25_detki_snegoviki",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 26,
    name: `Елочка Огоньки`,
    description: ``,
    weight: `400`,
    price: `600`,
    folder: "26_elki_ogonki",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 27,
    name: `Новогоднее Чудо`,
    description: ``,
    weight: `460`,
    price: `690`,
    folder: "27_novogodnee_chudo",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 28,
    name: `Снежинка`,
    description: ``,
    weight: `350`,
    price: `550`,
    folder: "28_snezhinka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 29,
    name: `Праздник Большой`,
    description: ``,
    weight: `520`,
    price: `800`,
    folder: "29_prazdnik_bolshoi",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 30,
    name: `Новогоднее Веселье`,
    description: ``,
    weight: `500`,
    price: `800`,
    folder: "30_novogodnee_veselie",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 31,
    name: `Снеговичок`,
    description: ``,
    weight: `180`,
    price: `320`,
    folder: "31_snegovichok",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 32,
    name: `Ушастик`,
    description: ``,
    weight: `300`,
    price: `500`,
    folder: "32_ushastik",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 33,
    name: `СантаФон`,
    description: ``,
    weight: `410`,
    price: `700`,
    folder: "33_santafon",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 34,
    name: `Северный Узор / Северная Сказка`,
    description: ``,
    weight: `350`,
    price: `600`,
    folder: "34_severnyi_uzor",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 35,
    name: `Часы`,
    description: ``,
    weight: `660`,
    price: `1150`,
    folder: "35_chasy",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 36,
    name: `Ребусы Загадки`,
    description: ``,
    weight: `350`,
    price: `555`,
    folder: "36_rebusy_zagadki",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 37,
    name: `Город Гномов`,
    description: ``,
    weight: `450`,
    price: `850`,
    folder: "37_gorod_gnomov",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 38,
    name: `Мышкина Книжка`,
    description: ``,
    weight: `380`,
    price: `650`,
    folder: "38_myshkina_knizhka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 39,
    name: `Письмо Деда Мороза`,
    description: ``,
    weight: `420`,
    price: `660`,
    folder: "39_pismo_deda_moroza",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 40,
    name: `Лесные Непоседы`,
    description: ``,
    weight: `415`,
    price: `700`,
    folder: "40_lesnye_neposedy",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 41,
    name: `Мышонок Пик`,
    description: ``,
    weight: `400`,
    price: `700`,
    folder: "41_myshonok_pik",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 42,
    name: `Подарок от Снегурочки`,
    description: ``,
    weight: `560`,
    price: `1000`,
    folder: "42_podarok_ot_snegurochki",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 43,
    name: `Веселый Грузовик`,
    description: ``,
    weight: `850`,
    price: `1500`,
    folder: "43_veselyi_gruzovik",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 44,
    name: `Милашка`,
    description: ``,
    weight: `620`,
    price: `1200`,
    folder: "44_milashka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 45,
    name: `Мышонок Марс`,
    description: ``,
    weight: `610`,
    price: `1100`,
    folder: "45_myshonok_mars",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 46,
    name: `Подарок для Ребят`,
    description: ``,
    weight: `500`,
    price: `900`,
    folder: "46_podarok_dlya_rebyat",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 47,
    name: `Золотое Сияние`,
    description: ``,
    weight: `530`,
    price: `950`,
    folder: "47_zolotoe_siyanie",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 48,
    name: `Ночной Город`,
    description: ``,
    weight: `400`,
    price: `760`,
    folder: "48_nochnoi_gorod",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 49,
    name: `Волшебная Избушка`,
    description: ``,
    weight: `540`,
    price: `1000`,
    folder: "49_volshebnaya_izbushka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 50,
    name: `Снежинка Большая`,
    description: ``,
    weight: `620`,
    price: `1250`,
    folder: "50_snezhinki_bolshie",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 51,
    name: `Волшебство`,
    description: ``,
    weight: `650`,
    price: `1250`,
    folder: "51_volshebstvo",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 52,
    name: `Лапландия`,
    description: ``,
    weight: `650`,
    price: `1200`,
    folder: "52_laplandiya",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 53,
    name: `Желаем Счастья`,
    description: ``,
    weight: `650`,
    price: `1300`,
    folder: "53_zhelaem_schastiya",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 54,
    name: `Дед Мороз и Снегурочка`,
    description: ``,
    weight: `620`,
    price: `1200`,
    folder: "54_ded_moroz_snegurochka",
    images: [
      "cover.jpg",
      "cover_2.jpg",
      "back.jpg",
      "back_2.jpg",
      "display.jpg",
      "pile.jpg",
    ],
  },
  {
    id: 55,
    name: `Мишутка`,
    description: ``,
    weight: `420`,
    price: `1700`,
    folder: "55_mishutka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 56,
    name: `Джинсовый Пенал`,
    description: ``,
    weight: `275`,
    price: `1200`,
    folder: "56_penal",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 57,
    name: `Джек и Стёпа`,
    description: ``,
    weight: `860`,
    price: `1900`,
    folder: "57_dzhek_i_styopa",
    images: [
      "cover.jpg",
      "cover_2.jpg",
      "back.jpg",
      "back_2.jpg",
      "display.jpg",
      "pile.jpg",
    ],
  },
  {
    id: 58,
    name: `Юрта`,
    description: ``,
    weight: `720`,
    price: `1500`,
    folder: "58_yurta",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 59,
    name: `Чудеса Случаются`,
    description: ``,
    weight: `510`,
    price: `1000`,
    folder: "59_chudesa_sluchaiutsya",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 60,
    name: `Новогодняя Сказка`,
    description: ``,
    weight: `740`,
    price: `1500`,
    folder: "60_novogodnyaya_skazka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 61,
    name: `Замок`,
    description: ``,
    weight: `1000`,
    price: `2300`,
    folder: "61_zamok",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 62,
    name: `Снежная Королева`,
    description: ``,
    weight: `1150`,
    price: `2500`,
    folder: "62_snezhnaya_koroleva",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 63,
    name: `Фабрика Новогодних Подарков`,
    description: ``,
    weight: `740`,
    price: `1500`,
    folder: "63_fabrika",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 64,
    name: `Колокол`,
    description: ``,
    weight: `615`,
    price: `1200`,
    folder: "64_kolokol",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 65,
    name: `Приключения с Гномами`,
    description: ``,
    weight: `1120`,
    price: `2150`,
    folder: "65_priklucheniya_s_gnomami",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 66,
    name: `Ёлка`,
    description: ``,
    weight: `650`,
    price: `1300`,
    folder: "66_elka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 67,
    name: `Посылка 48 Марок`,
    description: ``,
    weight: `1230`,
    price: `2400`,
    folder: "67_posylka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 68,
    name: `Сказки Деда Мороза`,
    description: ``,
    weight: `1220`,
    price: `2400`,
    folder: "68_skazki_deda_moroza",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 69,
    name: `Догони Деда Мороза`,
    description: ``,
    weight: `575`,
    price: `1200`,
    folder: "69_dogoni",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 70,
    name: `Ларец Ретро`,
    description: ``,
    weight: `615`,
    price: `1200`,
    folder: "70_larets",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 71,
    name: `Новогоднее Путешествие`,
    description: ``,
    weight: `1160`,
    price: `2900`,
    folder: "71_novogodnee_puteshestvie",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 72,
    name: `Почтовый Ларец / Рюкзак`,
    description: ``,
    weight: `1070`,
    price: `2100`,
    folder: "72_pochtovyi_larets",
    images: [
      "cover.jpg",
      "cover_2.jpg",
      "back.jpg",
      "back_2.jpg",
      "display.jpg",
      "pile.jpg",
    ],
  },
  {
    id: 73,
    name: `Дорогой Подарок`,
    description: ``,
    weight: `1100`,
    price: `2230`,
    folder: "73_dorogoi_podarok",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 74,
    name: `Чудеса Деда Мороза`,
    description: ``,
    weight: `1000`,
    price: `2320`,
    folder: "74_chudesa_deda_moroza",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 75,
    name: `В Новогоднюю Ночь`,
    description: ``,
    weight: `1670`,
    price: `3000`,
    folder: "75_v_novogodnyuiu_noch",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 76,
    name: `Книга Космос`,
    description: ``,
    weight: `1160`,
    price: `2500`,
    folder: "76_kniga_kosmos",
    images: ["cover.jpg", "back.jpg", "back_2.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 78,
    name: `Книга Зоопарк`,
    description: ``,
    weight: `1160`,
    price: `2500`,
    folder: "78_kniga_zoopark",
    images: ["cover.jpg", "back.jpg", "back_2.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 79,
    name: `Календарь`,
    description: ``,
    weight: `600`,
    price: `2000`,
    folder: "79_kalendar",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 80,
    name: `Сказочная Дружина`,
    description: ``,
    weight: `1160`,
    price: `2500`,
    folder: "80_druzhina",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 81,
    name: `Щедрый Подарок`,
    description: ``,
    weight: `2000`,
    price: `4850`,
    folder: "81_shedryi_podarok",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 82,
    name: `Семейка`,
    description: ``,
    weight: `800`,
    price: `1900`,
    folder: "82_semeika",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 83,
    name: `Веселые Мышата`,
    description: ``,
    weight: `500`,
    price: `1870`,
    folder: "83_veselye_myshata",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 84,
    name: `Золотой Подарок`,
    description: ``,
    weight: `1250`,
    price: `2900`,
    folder: "84_zolotoi_podarok",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 85,
    name: `Деревянная Посылка`,
    description: ``,
    weight: `2000`,
    price: `4900`,
    folder: "85_derevyannaya_posylka",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 56,
    name: `Джип`,
    description: ``,
    weight: `600`,
    price: `2000`,
    folder: "86_dzhip",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 87,
    name: `Рюкзак Мышонок`,
    description: ``,
    weight: `800`,
    price: `3900`,
    folder: "87_ryukzak_myshonok",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 88,
    name: `Счастливая Семейка`,
    description: ``,
    weight: `755`,
    price: `4300`,
    folder: "88_schshastlivaya_semeika",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 89,
    name: `Санта`,
    description: ``,
    weight: `610`,
    price: `4300`,
    folder: "89_santa",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 90,
    name: `Пиратский Сундук`,
    description: ``,
    weight: `740`,
    price: `2300`,
    folder: "90_piratskii_sunduk",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 91,
    name: `Снек`,
    description: ``,
    weight: `800`,
    price: `3800`,
    folder: "91_snek",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 92,
    name: `Пушистик`,
    description: ``,
    weight: `800`,
    price: `3900`,
    folder: "92_pushistik",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 93,
    name: `Мистер Мышь`,
    description: ``,
    weight: `800`,
    price: `4100`,
    folder: "93_mister_mysh",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 94,
    name: `Подушка Марсик`,
    description: ``,
    weight: `700`,
    price: `4000`,
    folder: "94_marsik",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
  {
    id: 95,
    name: `Рюкзак Микки`,
    description: ``,
    weight: `550`,
    price: `3900`,
    folder: "95_mikki",
    images: ["cover.jpg", "back.jpg", "pile.jpg", "display.jpg"],
  },
];
